# Migrations Kit Bundle
# https://github.com/nowo-tech/migrations-kit-bundle
# Use SchemaChecker and MigrationDefinitionRunner in Doctrine Migrations. See README for examples.

nowo_migrations_kit:
    # Doctrine connection name used by SchemaChecker when injected as service (e.g. bin/console)
    connection: default
